---
title: "Creating the Interactive Plots"
output: 
  html_document
---

To see the interactive plots described below, click [here](https://mb4650.shinyapps.io/plotly/).

### Evolution of the Interactive Plots

When looking at the data for the project, we wanted to create graphs and maps that look similar to what is seen in the news, but add an interactive aspect that allows users to look at the specific information they are interested in. For example, if a user to see the trends in cases over the year in their specific state, we wanted to create a map that would let them look at that specifically. We also wanted a map that allowed users to see what cases looked like across the US. One of the initial questions also included looking at how temperature and COVID-19 were correlated, however the NOAA dataset we used for temperature values has many missing values. Weather data was still included in the form of monthly trend graphs by state and in the hover in the map. However there many datapoints are missing, and we were not able to analyze temperature in the US the way we originally intended. 

### Data

COVID-19 data was obtained from the `COVID19` package, and was filtered to include only information for the US until 10/31/2020 to match the dates in the NOAA dataset. This dataset included information on the date, state, as well as the number of cases, tests, and hospitalizations for that given day. 

The other dataset used for this section was from the `rnoaa` package. The NOAA dataset included the daily max, min, and average temperatures, as well as thed daily precipitation from 10 randomly selected weather stations for each state, giving weather data from 500 stations between the 1/1/2020 and 10/31/2020. The temperatures were converted into Fahrenheit and averaged across the state for a given day, so there was only one datapoint per state per day.

The NOAA dataset was then joined with the COVID-19 one. 

This combined dataset was filtered and used to create the COVID-19 trends over time graphs.

To set the data up for the map, the date was separated into month, day, and year columns. Columns that were not needed for the visualizations were removed and new columns were created. The variables included: <br>

`id` - Unique state ID <br>
`key_apple_mobility` - State name <br>
`key_alpha_2` - State abbreviation <br>
`population` - State population <br>
`year` - Year the data is from <br>
`month` - Month the data is from <br>
`day` - Day the data is from <br>
`confirmed` - Number of confirmed COVID-19 cases <br>
`tests` - Number of COVID-19 tests <br>
`deaths` - Number of COVID-19 related deaths <br>
`hosp` - Numbe rof COVID-19 related hospitalizations <br>
`prop_cases` - Proportion of confirmed COVID-19 cases in the state <br>
`prop_deaths_pop` - Proportion of COVID-19 related deaths in the state <br>
`prop_deaths_case` - Proportion of COVID-19 related deaths among the confirmed cases in the state <br>
`prop_hospital_pop` - Proportion of COVID-19 related hospitalizations in the state <br>
`prop_hospital_case` - Proportion of COVID-19 related hospitalizations among confirmed cases in the state <br>
`prop_tested` - Proportion of the state tested for COVID-19 <br>
`new_cases` - Number of new <br>
`state_tavg` - Average state temperature <br>
`state_tmax` - Max state temperature <br>
`state_tmin` - Min state temperature <br>
`state_prcp` - Average precipitation level <br>

The dataset was then pivoted longer to create `covid_stat_type` and `covid_stat`, which included the names of the COVID-19 related variables and the associated value, respectively. We pivoted longer once more to get `noaa_stat_type` and `noaa_stat`, so the names of the NOAA related variables were in one column and their associated value in another. This ensured that we could filter by the appropriate values when creating the interactive map. 

The temperature plots used the NOAA dataset. The data were grouped and new variables averages of the temperature and precipitation variables were created to obtain the average for the month.


### Plots 

Our first tab contains COVID-19 trends over time in all 50 states. One graph shows cumulative COVID-19 cases, another shows COVID-19 hospitalizations, another shows cumulative COVID-19 death counts, and one overlays all three on top of each other so the user could compare the data simultaneously. They can select which state they want to see trends for with the drop-down menu on the left hand side. 

Our second tab shows a map of the United States containing information on COVID-19 data as well as climate data for all 50 states. On the side bar, the user can choose the month, date, COVID-19 variable, and climate variable that they want to look at, and they can hover over each state on the map to see the statistic of the COVID-19 variable and the climate variable selected for the month and day. Colors of the different states on the map are dependent on the COVID-19 variable selected. The COVID-19 variables included are: Number of Confirmed Cases, Number of Deaths, Number of Hospitalizations, Number of New Cases, Number of Tests, Proportion of Confirms Cases who Died of COVID-19, Proportion of Confirmed Cases who were Hospitalized with COVID-19, Proportion of State Population who Died of COVID-19, Proportion of State Population who were Hospitalized with COVID-19, Proportion of State Population who were Tested, and Proportion of State Population with Confirmed Cases. The climate variables included are: Average temperature, Maximum temperature, Minimum temperature, and Precipitation.

Our third tab shows a bar graph of the monthly average minimum temperature (F), maximum temperature (F), and average temperature(F) across 10 stations per state from January 2020 to October 2020. States were included based off of whether or not they had data for maximum temperature. The sidebar has a drop-down menu that allows you to choose which state you would like to see temperature trends for. The minimum and maximum temperature data are displayed are bars while the average temperature data is displayed as a line overlaid on top of the bars.

