---
title: "Plotly Graphics"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
runtime: shiny
---

```{r setup,include=FALSE}
library(tidyverse)
library(COVID19)
library(flexdashboard)
library(plotly)
```

```{r}
#level = 2 gives state level data and raw = false cleans the dataset
covid_dataset = covid19(c("US"), level = 2, raw = FALSE, verbose = FALSE) %>%
  janitor::clean_names() %>%
  filter(date <= '2020-10-31')

noaa = read_csv("data/noaadata.csv")%>%
        select (-c(X1))%>%
        janitor::clean_names()

noaa_avg = noaa %>%
  mutate(
    tavg = ((tavg/10)*1.8) + 32 ,
    tmax = ((tmax/10)*1.8) + 32,
    tmin = ((tmin/10)*1.8) + 32,
  ) %>%
  group_by(state, date) %>%
  summarize(
    state_tavg = mean(tavg, na.rm = TRUE),
    state_tmax = mean(tmax, na.rm = TRUE),
    state_tmin = mean(tmin, na.rm = TRUE),
    state_prcp = mean(prcp, na.rm = TRUE)
  )
  

covid_noaa_dataset = 
  full_join(covid_dataset,noaa_avg, by = c("key_alpha_2" = "state", "date" = "date")) %>%
  mutate(as.Date(date))
  

plot_df = 
  covid_noaa_dataset %>%
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>%
  select(id:population, key_apple_mobility, key_alpha_2, state_tavg:state_prcp) %>%
  mutate(
    prop_cases = confirmed/population,
    prop_deaths_pop = deaths/population,
    prop_deaths_case = deaths/confirmed,
    prop_hospital_pop = hosp/population,
    prop_hospital_case = hosp/confirmed,
    prop_tested = tests/population
  ) %>%
  group_by(key_alpha_2) %>%
  mutate(new_cases = (confirmed - lag(confirmed))) %>%
  select(key_apple_mobility, key_alpha_2, id, population, year:confirmed, deaths, hosp, prop_cases:new_cases) %>%
  pivot_longer(
    (tests:new_cases),
    names_to = "stat_type",
    values_to = "stat"
  ) %>%
  mutate(
    stat_name = 
    if_else(stat_type == "tests", "Number of Tests", 
    if_else(stat_type == "confirmed", "Number of Confirmed Cases",
    if_else(stat_type == "deaths", "Number of Deaths",
    if_else(stat_type == "hosp", "Number of Hospitalizations",
    if_else(stat_type == "prop_cases", "Proportion of State Population with Confirmed Cases",
    if_else(stat_type == "prop_deaths_pop", "Proportion of State Population who Died of COVID-19",
    if_else(stat_type == "prop_deaths_case", "Proportion of Confirmed Cases who Died of COVID-19",
    if_else(stat_type == "prop_hospital_pop","Proportion of State Population who were Hospitalized with COVID-19",
    if_else(stat_type == "prop_hospital_case", "Proportion of Confirmed Cases who were Hospitalized with COVID-19",
    if_else(stat_type == "prop_tested", "Proportion of State Population who were Tested",
    if_else(stat_type == "new_cases", "Number of New Cases", NULL))))))))))),
    month_name = month.name[month]
  )
  
plot2_df = 
  covid_noaa_dataset %>%
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>%
  select(id:population, key_apple_mobility, key_alpha_2, state_tavg:state_prcp) %>%
  mutate(
    prop_cases = confirmed/population,
    prop_deaths_pop = deaths/population,
    prop_deaths_case = deaths/confirmed,
    prop_hospital_pop = hosp/population,
    prop_hospital_case = hosp/confirmed,
    prop_tested = tests/population
  ) %>%
  group_by(key_alpha_2) %>%
  mutate(new_cases = (confirmed - lag(confirmed))) %>%
  select(key_apple_mobility, key_alpha_2, id, population, year:confirmed, deaths, hosp, prop_cases:new_cases, state_tavg:state_prcp) %>%
  pivot_longer(
    (tests:new_cases),
    names_to = "covid_stat_type",
    values_to = "covid_stat"
  ) %>%
    pivot_longer(
    (state_tavg:state_prcp),
    names_to = "noaa_stat_type",
    values_to = "noaa_stat"
  ) %>%
  mutate(
    noaa_stat_name = 
    if_else(noaa_stat_type == "state_tavg", "Average temperature",
    if_else(noaa_stat_type == "state_tmax", "Maximum temperature",
    if_else(noaa_stat_type == "state_tmin", "Minimum temperature",
    if_else(noaa_stat_type == "state_prcp", "Precipitation", NULL)))),
    covid_stat_name = 
    if_else(covid_stat_type == "tests", "Number of Tests", 
    if_else(covid_stat_type == "confirmed", "Number of Confirmed Cases",
    if_else(covid_stat_type == "deaths", "Number of Deaths",
    if_else(covid_stat_type == "hosp", "Number of Hospitalizations",
    if_else(covid_stat_type == "prop_cases", "Proportion of State Population with Confirmed Cases",
    if_else(covid_stat_type == "prop_deaths_pop", "Proportion of State Population who Died of COVID-19",
    if_else(covid_stat_type == "prop_deaths_case", "Proportion of Confirmed Cases who Died of COVID-19",
    if_else(covid_stat_type == "prop_hospital_pop","Proportion of State Population who were Hospitalized with COVID-19",
    if_else(covid_stat_type == "prop_hospital_case", "Proportion of Confirmed Cases who were Hospitalized with COVID-19",
    if_else(covid_stat_type == "prop_tested", "Proportion of State Population who were Tested",
    if_else(covid_stat_type == "new_cases", "Number of New Cases", NULL))))))))))),
    month_name = month.name[month]
  )
  
```


Trends in Cases, Hospitalizations, and Death for each State
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------


```{r}

# State list
state_sel = plot_df %>% pull(key_apple_mobility) %>% unique() %>% sort()


# Select state 
selectInput("state_sel", 
            label = h3("Select state"),
						choices = state_sel,
						selected = "Alabama")


```


Column {.tabset data-width=650}
-----------------------------------

### Chart A

```{r}
renderPlotly({
  covid_noaa_dataset %>%
    filter(
      key_apple_mobility == input[["state_sel"]]
    ) %>%
  plot_ly(
    x= ~date) %>% 
    add_lines(y = ~confirmed, name = 'Confirmed Cases', color = I("mediumpurple")) %>%
    add_lines(y = ~deaths, name = 'Deaths', color = I("mediumaquamarine")) %>%
    add_lines(y = ~hosp, name = 'Hospitalized', color = I("lightsalmon")) %>%
  layout(title = 'COVID-19 trends over time for confirmed cases, deaths, and hospitalization',
         xaxis = list(title = 'Date'),
         yaxis = list(title = 'Count'))
    
})
```

### Trend graphs


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
  covid_noaa_dataset %>%
    filter(
      key_apple_mobility == input[["state_sel"]]
    ) %>%
  plot_ly(
    x= ~date, y = ~confirmed, type = "bar", color = I("mediumpurple")) %>%
  layout(title = 'Confirmed COVID-19 Cases Over Time',
         xaxis = list(title = 'Date'),
         yaxis = list(title = 'Count'))
})
```

### Chart C

```{r}
renderPlotly({
  covid_noaa_dataset %>%
    filter(
      key_apple_mobility == input[["state_sel"]]
    ) %>%
  plot_ly(
    x= ~date, y = ~deaths, type = "bar", color = I("mediumaquamarine")) %>%
  layout(title = 'COVID-19 Deaths Over Time',
         xaxis = list(title = 'Date'),
         yaxis = list(title = 'Count'))
})
```


### Chart D

```{r}
renderPlotly({
  covid_noaa_dataset %>%
    filter(
      key_apple_mobility == input[["state_sel"]]
    ) %>%
  plot_ly(
    x= ~date, y = ~hosp, type = "bar", color = I("lightsalmon")) %>%
  layout(title = 'COVID-19 Hospitalization Cases Over Time',
         xaxis = list(title = 'Date'),
         yaxis = list(title = 'Count'))
})
```




Trends in COVID and Climate in US Between Jan 2020 and Oct 2020
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------


```{r}

# Select State, Month, Day

day = c(1:31)
covid_var_choice = plot2_df %>% pull(covid_stat_name) %>% unique() %>% sort()
noaa_var_choice = plot2_df %>% pull(noaa_stat_name) %>% unique() %>% sort()
month = plot2_df %>% pull(month_name) %>% unique()

# Select month 
selectInput("month_sel", 
            label = h3("Select month"),
						choices = month,
						selected = "January")

# Select day
selectInput("day_sel", 
            label = h3("Select day"),
						choices = as.list(day),
						selected = 1)

# Covid Variable select
selectInput("covid_variable_choice", label = h3("Select COVID variable"),
						choices = covid_var_choice, selected = "Number of Tests")

# NOAA Variable select
selectInput("noaa_variable_choice", label = h3("Select climate variable"),
						choices = noaa_var_choice, selected = "Average temperature")
```

Column {.tabset}
-----------------------------------------------------------------------

### US Map
```{r map}

renderPlotly({
  plot2_df %>%
    filter(
      month_name == input[["month_sel"]],
      day == input[["day_sel"]],
      covid_stat_name == input[["covid_variable_choice"]],
      noaa_stat_name == input[["noaa_variable_choice"]]
    ) %>%
  plot_geo(locationmode = 'USA-states') %>% 
  add_trace(
    z = ~covid_stat,
    locations = ~key_alpha_2,
    color = ~covid_stat, 
    colors = "Reds",
    text = ~paste(covid_stat_name, noaa_stat, noaa_stat_name, sep = "<br>")
  ) %>% 
    colorbar(title = "COVID Statistic") %>% 
    layout(
    title = 'United States Map - Statistics by State',
    geo = list(
      scope = 'usa',
      projection = list(type = 'state'),
      showlakes = TRUE,
      lakecolor = toRGB('white')
  ))
})

```

### Description
Description of US map

```{r, ignore = TRUE}
month_noaa_avg = 
    noaa_avg %>%
    separate(date, into = c("year", "month", "day"), convert = TRUE) %>%
    group_by(state, month) %>%
    summarize(
      month_tavg = mean(state_tavg, na.rm = TRUE),
      month_tmax = mean(state_tmax, na.rm = TRUE),
      month_tmin = mean(state_tmin, na.rm = TRUE),
      month_prcp = mean(state_prcp, na.rm = TRUE)) %>%
   filter(!is.na(month_tmax))
```


Trends in Temperature for each State
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------
```{r}

# State list
state_month_sel = month_noaa_avg %>% pull(state) %>% unique() %>% sort()


# Select state 
selectInput("state_month_sel", 
            label = h3("Select state"),
						choices = state_month_sel,
						selected = "AK")

```

Column {.tabset}
-----------------------------------------------------------------------

### Temperature Trends

```{r}
renderPlotly({
    month_noaa_avg %>%
    filter(
      state == input[["state_month_sel"]]
    ) %>%
  plot_ly(
    x= ~month, y = ~month_tmin, type = "bar", name = "Minimum temperature", color = "mediumvioletred") %>%
    add_trace(y = ~month_tmax, type = "bar",name = "Maximum temperature", color = "mistyrose") %>%
    add_lines(y = ~month_tavg, name = "Average temperature", color = "magenta")%>%
    layout(title = 'Temperature Trends Over Time',
           xaxis = list(title = 'Date'),
           yaxis = list(title = 'Temperature (F)'))

})
```

### Description
Description of temperature trends
