---
title: "CACTUS Project Report"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Motivation

Our motivation for CACTUS came from the idea that weather potentially had an effect on COVID-19 transmission. As we’re now about to enter the winter months, it is more paramount than ever that we understand this relationship, so that the general public can be appropriately informed and take proper precaution and control measures as a result. Although climate itself most likely does not act alone in contributing to transmission, we were interested in further understanding the association between various climate variables and COVID-19 statistics, in addition to other social and political variables. Our project utilizes real life COVID-19 and climate data to analyze trends and create predictive models.

# Initial Questions

Our initial questions involved looking deeper into trends in COVID-19 over the year and how those trends were affected by climate. We also wanted to see what the case counts might look like in the future based on the data that we have. To answer these broader questions, we divided into multiple smaller sections to better address more specific questions. For more information on what these initial questions looked like and how they evolved over time, please click on one of the following:

#### [Descriptives](descriptive_plotly.html)

#### [Interactive Dashboard Visualizations](create_shiny.html)

#### [Regression Analysis](regression_analysis.html)



# Data

For each section, COVID-19 data were obtained from the `COVID19` package^1^ in R. Additional datasets were utilized for the analysis and are defined in the following reports.

#### [Descriptives](descriptive_plotly.html)

For descriptive visualizations, we retrieved data from the aforementioned `COVID19` package^1^ in R, JHU CSSE database^2^, and the `sars2pack`^3^ from GitHub along with two locally created datasets with date of mask mandate per state and important national events. 

#### [Interactive Dashboard Visualizations](create_shiny.html)

For interactive dashboard visualizations, we retrieved our data from the `COVID19` package^1^ in R as well as the `rnoaa` dataset.

#### [Regression Analysis](regression_analysis.html)

For the regression analysis, we used the `COVID19` package^1^ in R as well as the noaa dataset. We created a separate dataset for the regression model and the predictive tool and pulled in the variables that we are interested in to run the analysis.


# Discussion of Exploratory Analysis 

Exploratory analysis was done in [Descriptives](descriptive_plotly.html) as well as [Interactive Dashboard Visualizations](create_shiny.html). 

The purpose and results were to see whether there are any differences between new daily COVID-19 cases and deaths between states that are temperate and sub-tropical, red/blue states as per 2020 election, and between US cities among those that are the most populated compared to 10 randomly selected less populated counties. Additionally, the interactive dashboard explored the data individually focusing on COVID-19 data and climate data. 

Our results show that COVID-19 cases dropped from April to May, but increased again in the summer, before decreasing in August and September, and peaking again as we got closer to the winter. We see that COVID-19 deaths peaked at the beginning of the pandemic around March and April before decreasing. The pattern of COVID-19 cases is similar between sub-tropical and temperate states, but the total count in cases in sub-tropical states is slightly higher and fluctuates more, with similar observations for COVID-19 deaths. Patterns for populated cities and less populated counties are similar; however, the peaks for COVID-19 cases and deaths are more pronounced for populated cities. From our visualizations, COVID-19 cases and deaths do not seem to be responsive to national events. However, as we move into the winter months, cases and deaths are increasing, but we are not sure if that is a result of the national events in the fall and winter.

The interactive dashboard showed that the cumulative COVID-19 cases and deaths have increased over time since January 2020 up till October 2020. However, the rate at which cases are increasing is much faster than the rate at which deaths are increasing, as shown by the graphs in the first tab in the interactive dashboard. COVID-19 hospitalization cases fluctuate over time from state to state, so no conclusive trends can be assumed from the data that we have on COVID-19 hospitalizations. When looking at trends for temperature for each state, we see a similar trend in each state, showing an increase in temperature (minimum/maximum/average) from January 2020 till August 2020, and then a decrease in temperatures going into October 2020. 

# Discussion of Predictive Models

The formal analysis for the predictive model was done in [Regression Analysis](regression_analysis.html) and the predictive tool can be found here [Predictive Tool](https://gaurib2685.shinyapps.io/predictive_interactive_map/).

We wished to check for the association between new COVID-19 cases and various climate variables such as average temperature and precipitation. Additionally, we believe that it was important to factor in various variables such as policy changes and restrictions. Therefore, we created three models that would assist in predicting the future case counts based on these variables. 

First model: 
In the first model, we developed a negative binomial regression model to assess the relationship between the new COVID-19 cases that arise in various states, and climate variables such as average temperature and precipitation. We accounted for multicollinearity between these continuous variables by doing a co-linearity check. We proceeded to develop the negative binomial regression owing to the smaller AIC values for the model. 

Our results show that the number of case counts significantly decrease with increase in temperatures. However, the case counts do not show significant association with the total precipitation when adjusted for month and states. 
With every degree Fahrenheit increase in average temperature, the number of cases decrease by 4.3%. This association is significant at the 5% level of significance. This supports our hypothesis that the number of cases would rise with a decrease in temperature. Therefore, there is a possibility that we would expect more cases in winter.   

However, there could also be other factors that come into play which can influence this relationship, such as governmental restrictions and public health campaigns and discourse. To account for this, we included variables such as school closures, work place closures, and gathering restrictions into our second model. 

Second model: 
We found a significant association between the number of new case counts and workplace restrictions, at the 5% level of significance. 
Our second model suggests that the number of case counts decreases for required closing of some sectors of workplaces as compared to no workplace restriction measures by 30%. 
With every degree Fahrenheit increase in average temperature, the number of cases decrease by 3.7%, adjusting for school, workplace, and gathering restrictions. This association is significant at the 5% level of significance. This supports our hypothesis that the number of cases would rise with a decrease in temperature.

Third model: 
We did not find a significant association between policies, such as information campaigns and contact tracing, and the number of new cases, while controlling for temperature. 
With every degree Fahrenheit increase in average temperature, the number of cases decrease by 4.3%, adjusting for information campaigns and contact tracing. This association is significant at the 5% level of significance. This supports our hypothesis that the number of cases would rise with a decrease in temperature.

Conclusion: 

According to this [study](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7463156/)^4^, there was a negative correlation between atmospheric temperature variations and daily new cases growth rates. Our main findings corroborated their results and supported our main hypothesis that the number of new cases would rise with a decrease in temperature.

# Project experience

Overall we enjoyed our project experience! We hope you enjoy navigating through our website and learning more about COVID-19 and climate. 

The descriptive visualizations evolved a lot from what we initially wanted it to be as we further explored the data that we had. Due to discrepancies and limited variables in the data, there were things that we were able to do and could not do depending on missing data. Our results from the descriptive visualizations suggest that there may be a potential relationship between some individual variables we analyzed and COVID-19; however, we cannot make any conclusions since potential confounders were not controlled for. Originally, we wanted to do a three-level analysis, comparing data on the national, state, and city/county levels. Unfortunately, we could not use the same data source for all three levels (aggregating lower-level data to obtain top-level data) due to discrepancies in data collection. As a result, we had to use three separate data sources for each level, allowing us to only compare within but not between each level. Although a bit more challenging, it was rewarding to be able to find the relevant data sources and create the graphics we wanted in order to depict patterns of COVID-19 cases and deaths corresponding with multiple factors. 

For the interactive dashboard visualizations, creating the shiny app was a new experience that we are glad we got to apply outside of class. Although our original plan was to do a day-by-day comparison of COVID-19 and climate, we were unable to because there was a lot of missing temperature data. We ended up having to change what we wanted to plot due to this. A lot of what we did was tinkering with the Shiny app to see what would and wouldn't work, which allowed us to learn a lot about Shiny in the process. An additional issue that would come up often was that deploying the Shiny app sometimes wouldn't show our desired results, which was at times frustrating because it was difficult to tell whether or not we had an error. Overall, it was very exciting to reach our final product with the interactive dashboard, and creating it in a way that was user friendly and aesthetically pleasing. 

When working on the regression analysis and the predictive model, the main challenge was figuring out the regression model and making sure it was correct, while also seeing how we could make the model fit the maps in a visually appealing way. Our regression analysis has several limitations - we primarily did not account for all the confounding variables, which may be the reason for our results being inconsistent with our hypothesis. More rigorous analysis would account for these discrepancies. Furthermore, we wanted to build on the regression models to help us predict the COVID-19 case counts based on temperature variation and we were successfully able to do so and map it out. This involved a lot of conceptualization to see how we would go from a model to a map, and making sure we formulated it in a way that would make sense for users. Seeing the final product after transmitting the regression models onto the map was very rewarding. 

Overall, barriers for the entire team mainly consisted of issues that dealt with committing and 
pushing/pulling are edits, as we were often working on the project simultaneously and ran into errors because of this. A unique experience with the timing of this project in particular was working on a collaborative project with others limited to an online format only, as we were only able to meet with each other online due to COVID-19. 

We had an enjoyable experience working as a team and applying concepts and material that we learned in class to relevant issues. Our topic of COVID-19 and climate was a very timely subject as we chose something that is affecting everyone's lives on many different levels, and used the available data to create a public-facing tool that could potentially be useful for people now and in the future. With this project, each one of us was constantly improvising and coming up with new ideas to add onto the website in a way that is coherent for users. This process itself was a unique experience, but also helped us develop a deeper and better understanding of the data and the methods used to analyze it. 


### Citations

1. Guidotti, E., Ardia, D., (2020), "COVID-19 Data Hub", Journal of Open Source Software 5(51):2376, doi: 10.21105/joss.02376.
  
2. Dong E, Du H, Gardner L. An interactive web-based dashboard to track COVID-19 in real time. Lancet Inf Dis. 20(5):533-534. doi: 10.1016/S1473-3099(20)30120-1.

3. https://github.com/seandavi/sars2pack.

4. Rouen, A., Adda, J., Roy, O., Rogers, E., & Lévy, P. (2020). COVID-19: relationship between atmospheric temperature and daily new cases growth rate. Epidemiology and infection, 148, e184. doi: 10.1017/S0950268820001831.
