<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>statistical Analyses</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/journal.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 61px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h2 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h3 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h4 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h5 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h6 {
  padding-top: 66px;
  margin-top: -66px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="about.html">About the Members</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="project_report.html">Project Report</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Interactive Dashboard Visualizations
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="create_shiny.html">Report on Creating Interactive Plots</a>
    </li>
    <li>
      <a href="https://mb4650.shinyapps.io/plotly/">View Interactive Shiny Dashboard</a>
    </li>
  </ul>
</li>
<li>
  <a href="descriptive_plotly.html">Descriptives</a>
</li>
<li>
  <a href="Regression-Analysis.html">Regression Analysis</a>
</li>
<li>
  <a href="predictive_tool.html">Predictive Tool</a>
</li>
<li>
  <a></a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">statistical Analyses</h1>

</div>


<pre><code>## ── Attaching packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
## ✓ tibble  3.0.3     ✓ dplyr   1.0.0
## ✓ tidyr   1.1.0     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.5.0</code></pre>
<pre><code>## ── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     date, intersect, setdiff, union</code></pre>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## 
## Attaching package: &#39;nlme&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     collapse</code></pre>
<pre><code>## This is mgcv 1.8-33. For overview type &#39;help(&quot;mgcv-package&quot;)&#39;.</code></pre>
<pre><code>## Loading required package: xml2</code></pre>
<pre><code>## 
## Attaching package: &#39;rvest&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     pluck</code></pre>
<pre><code>## The following object is masked from &#39;package:readr&#39;:
## 
##     guess_encoding</code></pre>
<div id="create-dataset-with-noaa-data" class="section level2">
<h2>Create dataset with noaa data</h2>
</div>
<div id="import-covid-datase.-clean-and-tidy-data" class="section level2">
<h2>Import Covid datase. Clean and tidy data</h2>
</div>
<div id="merging-the-two-dataset" class="section level2">
<h2>Merging the two dataset</h2>
<pre class="r"><code>covid_noaa_dataset =
  inner_join(covid_data,noaa_dataset, by = c(&quot;key_alpha_2&quot; = &quot;state_code&quot;, &quot;month&quot; = &quot;month&quot;)) %&gt;%
  mutate(
    month_name = month(ymd(date), label = TRUE, abbr = FALSE)
  ) %&gt;%
  rename(case_count = &quot;confirmed&quot;)
write_csv(covid_noaa_dataset, &quot;data/covid_noaa_dataset.csv&quot; )</code></pre>
</div>
<div id="hypothesis" class="section level2">
<h2>Hypothesis</h2>
<p>Our team hypothesizes that there is a relationship between temperature and COVID-19 cases.</p>
<div id="relevant-predictors" class="section level3">
<h3>Relevant predictors</h3>
<p>The following are the relevant predictors we want to include in the model</p>
<ul>
<li><code>new_cases</code>- The number of new cases in every month.</li>
<li><code>case_count</code> - The total number of cases in every month.</li>
<li><code>population</code>- Total population of each state - This forms the offset variable in the poisson regression model and the demoninator for the count to extrapolate the rate.</li>
<li><code>state_name</code>- All the states in the USA</li>
<li><code>state_tavg</code>- The average temperature in a state in a month.</li>
<li><code>state_tmax</code>- The maximum temperature in a state in a month</li>
<li><code>state_tmin</code>- The minimum temperature in a state in a month</li>
<li><code>state_total_prcp</code> - The total precipitation in a state in a month.</li>
</ul>
</div>
<div id="assessing-crude-correlation-among-our-selected-variables" class="section level3">
<h3>Assessing crude correlation among our selected variables</h3>
<pre class="r"><code>library(MASS)</code></pre>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<pre class="r"><code>covid_noaa_dataset_cor =
covid_noaa_dataset %&gt;%
  dplyr::select(new_cases, state_tavg, state_tmax, state_tmin, state_total_prcp)</code></pre>
<pre><code>## Adding missing grouping variables: `month`, `key_alpha_2`</code></pre>
<pre class="r"><code>  covid_noaa_dataset_cor[,3:7] %&gt;%
  cor() %&gt;%
  corrplot::corrplot(type = &quot;lower&quot;,
                     method = &quot;square&quot;,
                     addCoef.col = &quot;red&quot;,
                     diag = FALSE,
                     number.cex = .6,
                     tl.col = &quot;red&quot;,
                     tl.cex = .9,
                     tl.srt = 45)</code></pre>
<p><img src="Regression-Analysis_files/figure-html/unnamed-chunk-2-1.png" width="90%" /></p>
</div>
<div id="confounding" class="section level3">
<h3>Confounding</h3>
</div>
<div id="modeling---poisson-vs-negative-binomial-regression" class="section level3">
<h3>Modeling - Poisson vs Negative binomial regression</h3>
<pre class="r"><code>poisson_mod = glm(new_cases ~  as.factor(month) + state_tavg + state_total_prcp, 
                    family = &quot;poisson&quot;(link = &quot;log&quot;), data = covid_noaa_dataset)

poisson_mod %&gt;%
  broom::glance() %&gt;% 
  dplyr::select(AIC) %&gt;% 
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">28597532</td>
</tr>
</tbody>
</table>
<pre class="r"><code>neg_bin_mod = glm.nb(new_cases ~ as.factor(month) + state_tavg + state_total_prcp,
                            data = covid_noaa_dataset)

neg_bin_mod %&gt;% 
  broom::glance() %&gt;% 
  dplyr::select(AIC) %&gt;% 
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">9174.884</td>
</tr>
</tbody>
</table>
<p>Since the AIC for Poisson is 28597532 and the AIC for negative binomia regression model is 9174.884, we decided to proceed with negative binomial regression model</p>
</div>
</div>
<div id="cross-validation" class="section level2">
<h2>Cross validation</h2>
<pre class="r"><code>count_cv = 
  crossv_mc(covid_noaa_dataset, 100)
count_cv = 
  count_cv %&gt;% 
  mutate(  
    model_poisson = map(train, ~glm(new_cases ~  as.factor(month) + state_tavg + state_total_prcp,
                                    family=&quot;poisson&quot; (link = log), covid_noaa_dataset)), 
    model_neg_binomial = map(train, ~ glm.nb(new_cases ~  as.factor(month) + state_tavg + state_total_prcp, 
                                             data = covid_noaa_dataset))) %&gt;% 
  mutate(rmse_poisson = map2_dbl(model_poisson, test, ~rmse(model = .x, data = .y)), 
         rmse_negative_binomial = map2_dbl(model_neg_binomial, test, ~rmse(model = .x, data = .y)))

count_cv %&gt;% 
  dplyr::select(rmse_poisson, rmse_negative_binomial) %&gt;% 
  pivot_longer(
    everything(),
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;) %&gt;% 
  mutate(model = fct_inorder(model)) %&gt;% 
  ggplot(aes(x = model, y = rmse)) + geom_violin() +
  labs(
    title = &quot;Prediction Error Distributions&quot;
  )</code></pre>
<p><img src="Regression-Analysis_files/figure-html/unnamed-chunk-4-1.png" width="90%" /></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
