---
title: "statistical Analyses"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup}
library(tidyverse)
library(COVID19)
library(lubridate)
library(modelr)
library(mgcv)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Create dataset with noaa data

```{r}

tmin_df = read_csv("https://urldefense.proofpoint.com/v2/url?u=https-3A__www.ncdc.noaa.gov_cag_statewide_mapping_110-2Dtmin.csv&d=DwIFAg&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=B8uzIkNMhKdWydN9xY4NUSbhsqKRbTFG_gmZY3kin8Q&m=ilRLcOY5-22-ot8YTUHjYK-tstakLha43P2L-7wwJSc&s=hmGOQjY_Ej_kzF9vStPclRFQpAr4mQSKOX5ce_tmlsE&e= ", skip = 3) %>%
  janitor::clean_names() %>%
   separate(date, into = c("year", "month"), sep = 4) %>%
  mutate(
    month = as.numeric(month),
    state_code = state.abb[match(location,state.name)],
    state_name = location,
    state_tmin = value) %>%
  filter(year == 2020) %>%
  select(state_name,state_code, month, state_tmin)

tmax_df = read_csv("https://urldefense.proofpoint.com/v2/url?u=https-3A__www.ncdc.noaa.gov_cag_statewide_mapping_110-2Dtmax.csv&d=DwIFAg&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=B8uzIkNMhKdWydN9xY4NUSbhsqKRbTFG_gmZY3kin8Q&m=ilRLcOY5-22-ot8YTUHjYK-tstakLha43P2L-7wwJSc&s=kFXvvcnRWOVQuIlHG8ufptNh9-TGtc8HeymdMUmu_Dw&e= ", skip = 3) %>%
  janitor::clean_names() %>%
   separate(date, into = c("year", "month"), sep = 4) %>%
  mutate(
    month = as.numeric(month),
    state_code = state.abb[match(location,state.name)],
    state_name = location,
    state_tmax = value) %>%
  filter(year == 2020) %>%
  select(state_name,state_code, month, state_tmax)

tavg_df = read_csv("https://urldefense.proofpoint.com/v2/url?u=https-3A__www.ncdc.noaa.gov_cag_statewide_mapping_110-2Dtavg.csv&d=DwIFAg&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=B8uzIkNMhKdWydN9xY4NUSbhsqKRbTFG_gmZY3kin8Q&m=ilRLcOY5-22-ot8YTUHjYK-tstakLha43P2L-7wwJSc&s=wY9iFojIMOK8mzQ7AkPJQDUUj3FfapibffutaytqzXU&e= ", skip = 3) %>%
  janitor::clean_names() %>%
  separate(date, into = c("year", "month"), sep = 4) %>%
  mutate(
    month = as.numeric(month),
    state_code = state.abb[match(location,state.name)],
    state_name = location,
    state_tavg = value) %>%
  filter(year == 2020) %>%
  select(state_name,state_code, month, state_tavg)

prcp_df = read_csv("https://urldefense.proofpoint.com/v2/url?u=https-3A__www.ncdc.noaa.gov_cag_statewide_mapping_110-2Dpcp.csv&d=DwIFAg&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=B8uzIkNMhKdWydN9xY4NUSbhsqKRbTFG_gmZY3kin8Q&m=ilRLcOY5-22-ot8YTUHjYK-tstakLha43P2L-7wwJSc&s=VPeiJ1-NI637AZPZMfUV8exXyubpArhFG_u6KBXJlEI&e= ", skip = 3) %>%
  janitor::clean_names() %>%
  separate(date, into = c("year", "month"), sep = 4) %>%
  mutate(
    month = as.numeric(month),
    state_code = state.abb[match(location,state.name)],
    state_name = location,
    state_total_prcp = value) %>%
  filter(year == 2020) %>%
  select(state_name,state_code, month, state_total_prcp)

noaa_dataset =
  inner_join(tavg_df, tmin_df, by = c("state_name" = "state_name", "month" = "month", "state_code" = "state_code")) %>%
  inner_join(tmax_df, by = c("state_name" = "state_name", "month" = "month", "state_code" = "state_code")) %>%
  inner_join(prcp_df, by = c("state_name" = "state_name", "month" = "month", "state_code" = "state_code"))
```

## Import Covid datase. Clean and tidy data 

```{r}
#level = 2 gives state level data and raw = false cleans the dataset
covid_dataset = covid19(c("US"), level = 2, raw = FALSE, verbose = FALSE) %>%
  janitor::clean_names()

covid_data =
  covid_dataset %>%
  mutate(month = month(date),
         day = day(date),
         month = as.numeric(month),
         day = day(date)) %>%
  group_by(month, key_alpha_2) %>% top_n(1, day) %>%
  mutate(new_cases = confirmed - lag(confirmed, default = 0))
```

## Merging the two dataset 

```{r}
covid_noaa_dataset =
  inner_join(covid_data,noaa_dataset, by = c("key_alpha_2" = "state_code", "month" = "month")) %>%
  mutate(
    month = factor(month)
  ) %>%
  rename(case_count = "confirmed")
```
